### ISSUE TITLE
Scheduled action failure

### ISSUE THREAD

**Issue by Eomm** [nearform/actions-toolkit#34]
By using this module, when a scheduled action is triggered, the following error shows up:

```
Cannot read properties of undefined (reading 'full_name')
```

use case: https://github.com/Eomm/fastify-overview/actions/runs/2213965092

I think this function should be safe to run in this scenario.

**Comment by simoneb** [comment]
It looks like the schedule trigger does not have any webhook payload. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

I think we should be able to access the full name of a repo from the github context instead of the event payload. https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
